const SUBSCRIPTION_EVENTS = {
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_CREATED: "EVENT_CREATED",
    EVENT_DELETED: "EVENT_DELETED",

    FAVORITE_TIP_ADDED: "FAVORITE_TIP_ADDED",
    FAVORITE_TIP_REMOVED: "FAVORITE_TIP_REMOVED",
};

export default SUBSCRIPTION_EVENTS;
